name: Actions checkout workflow demo

# on: [push]
on:
  workflow_dispatch:
    branches:
      - master

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls
      - name: Checkout
        uses: actions/checkout@v1
      - name: List files
        run: |
          pwd
          ls
