name: ci flutter (ubuntu)
on:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  FLUTTER_VERSION: "2.8.1"
jobs:
  bootstrap:
    name: Bootstrap flutter
    #runs-on: macos-latest
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Show java version
      run: java -version
    - name: Get flutter sdk
      uses: subosito/flutter-action@v1
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
    - name: flutter config no analytics
      run: flutter config --no-analytics
    #- name: flutter accept android licenses
    #  run: flutter doctor --android-licenses
    - name: flutter doctor
      run: flutter doctor
    - name: flutter version
      run: flutter --version
    - run: flutter pub get
    #- run: flutter format --set-exit-if-changed .
    - run: flutter analyze
    - run: flutter test
    - run: flutter build apk --debug
    #- run: flutter build ios --release --no-codesign

