name: MacOS Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  tests:
    name: Tests
    runs-on: macos-latest
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "2.8.1"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: $JAVA_VERSION
    - name: Get flutter version
      uses: subosito/flutter-action@v1
      with:
        flutter-version: $FLUTTER_VERSION
    - run: flutter pub get
    - run: flutter analyze
    - run: flutter test
    - run: flutter build apk --debug

    # - name: Setup ruby
    #   uses: ruby/setup-ruby@v1
    #   with:
    #     ruby-version: 2.6.x
    #     bundler-cache: true
    #     bundler: 'Gemfile.lock'

    - name: Install Pods
      run: |
        pod install

    - name: Run tests
      run: |
        bundle exec fastlane tests
